blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_posts.urls')),
]

blog_posts/urls.py
from django.urls import path
from blog_posts import views
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'blog_posts'
urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.blog, name='blogs'),
    path('blog_entry/<int:blog_id>/', views.blog_entry, name='blog_entry'),
    path('add_blog/', views.add_blog, name='add_blog'),
    path('add_entry/<int:blog_id>/', views.add_entry, name='add_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name="edit_entry"),
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),
]

blog_posts/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class BlogEntry(models.Model):
    blog_entry_title = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=False)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    text = models.TextField()

    class Meta:
        verbose_name_plural = 'Blog Entries'

    def __str__(self):
        return f"{self.blog_entry_title[:50]}"

blog_posts/forms.py
from django import forms
from blog_posts.models import Blog, BlogEntry

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title'] # make an array
        label = {'title': ''} # make a dictionary

class EntryForm(forms.ModelForm):
    class Meta:
        model = BlogEntry
        fields = ['blog_entry_title', 'date_added', 'text']
        label = {'Title': '', 'Date Addded': '', 'Text': ''}

blog_posts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from .models import Blog, BlogEntry
from .forms import BlogForm, EntryForm
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    DeleteView,
)

# Create your views here.
def home(request):
    blogs = Blog.objects.order_by('date_added') # this is similar to Blog.objects.all() --> blogs = ['Blog 1', 'Blog 2']
    context = {'blogs':blogs} # dictionary 
    return render(request, 'blog_posts/base.html', context)

def blog(request):
    blogs = Blog.objects.order_by('date_added')
    context = {'blogs':blogs}
    return render(request, 'blog_posts/blog.html', context)

def blog_entry(request, blog_id):
    blog = Blog.objects.get(id=blog_id) # get the specific blog id
    entries = blog.blogentry_set.all() # this uses the 'many to one' relationship -> accessed through specific blog
    context = {'blog':blog, 'entries': entries}
    return render(request, 'blog_posts/entry.html', context)

def add_blog(request):
    # logic for 'POST' and 'GET' requests
    if request.method != 'POST':
        form = BlogForm()
    else:
        form = BlogForm(data=request.POST)

        # if form is valid, redirect to blog.html
        if form.is_valid():
            form.save()
            return redirect('blog_posts:blogs')

    # if blank or invalid -> go back to add_blog.html
    context = {'form': form}
    return render(request, 'blog_posts/add_blog.html', context)

def add_entry(request, blog_id):
    blog = Blog.objects.get(id=blog_id) # get parent 
    # logic for 'POST' and 'GET' requests
    if request.method != 'POST': # when the form is empty (when the user first visits the page)
        form = EntryForm()
    else: # when the form is full (the user submitted data)
        form = EntryForm(data=request.POST)

        if form.is_valid():
            entry = form.save(commit = False) # dont save it yet! we need to attach this form to the parent
            entry.blog = blog # make sure we add data from its parent
            entry.save() # save to database
            return redirect("blog_posts:blog_entry", blog_id=blog.id)

    context = {'form': form, 'blog': blog}
    return render(request, 'blog_posts/add_entry.html', context)

def edit_entry(request, entry_id):
    entry = BlogEntry.objects.get(id=entry_id)
    blog = entry.blog

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)

        if form.is_valid():
            form.save()
            return redirect('blog_posts:blog_entry', blog_id=blog.id)

    context = {
        'entry':entry,
        'blog':blog,
        'form':form
    }
    return render(request, 'blog_posts/edit_entry.html', context)


def delete_entry(request, entry_id):
    entry = BlogEntry.objects.get(id=entry_id)
    blog = entry.blog
    entry.delete()
    return redirect('blog_posts:blog_entry', blog_id=blog.id)

blog_posts/templates/blog_posts/add_blog.html
{% extends 'blog_posts/base.html' %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Add a Blog</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {% block content %}

        <div class="section-title"> 
            <h2>Add a new blog</h2>
        </div>

        <div class="add-blog-container">
            <form action="{% url 'blog_posts:add_blog' %}" method="post" class="form-contents">
                {% csrf_token %}
                {{form.as_p}}
                <button name="submit" class="add">Add blog</button>
            </form>
        </div>
        {% endblock content %}
        
        <script src="" async defer></script>
    </body>
</html>

blog_posts/templates/blog_posts/add_entry.html
{% extends 'blog_posts/base.html' %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title %}<title>Add an Entry</title>{% endblock title%}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {% block content %}
        <div class="section-title">
            <h2>Add a new entry</h2>
        </div>
        
        <div class="form-container">
            <form action="{% url 'blog_posts:add_entry' blog.id %}" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button class="add">Add entry</button>
            </form>
        </div>
        {% endblock content%}
        
        <script src="" async defer></script>
    </body>
</html>

blog_posts/templates/blog_posts/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title %}<title>Blog Home</title> {% endblock title %}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block styles %}
        {% load static %}
        <link rel="stylesheet" type = "text/css" href="{% static 'blog_posts/styles.css' %}">
        {% endblock styles %}
    </head>
    <body>
        <nav>
            <h1 id="logo"><a href="{% url 'blog_posts:home' %}">My Blog Space</a></h1>
            <ul>
                <li class="nav-item"><a href="{% url 'blog_posts:blogs' %}">Blogs</a></li>
            </ul>
        </nav>
        
        {% block content %}
        <div class="container">
            <div class="decorated-box">
                <h1 class="home-page">Write the details of your life.</h1>
            </div>
        </div>
        {% endblock content %}
        <script src="" async defer></script>
    </body>
</html>

blog_posts/templates/blog_posts/blog.html
{% extends 'blog_posts/base.html' %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title %}<title>Blogs</title>{% endblock title%}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {% block content %}

        <div class="section-title">
            <h2>Blogs</h2>
        </div>

        <div class="grid-container">
            <div class="grid">
                {% for blog in blogs %}
                    <p class="cell"><a href="{% url 'blog_posts:blog_entry' blog.id %}">{{ blog }} - {{ blog.date_added|date:'D, M n, Y' }}</a></p>
                {% empty %} <!-- output this if there is nothing in blogs section-->
                <p>You have no blogs yet...</p>
                {% endfor %}
            </div>
        </div>
        <div class="add-blog-btn">
            <button class="add"><a href="{% url 'blog_posts:add_blog' %}">Add a new blog<a></button>
        </div>

        {% endblock content %}
        <script src="" async defer></script>
    </body>
</html>

blog_posts/templates/blog_posts/edit_entry.html
{% extends 'blog_posts/base.html' %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title %} <title>Edit entry</title> {% endblock title %}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {% block content %}
        <h2>Edit the entry</h2> 
        <form action="{% url 'blog_posts:edit_entry' entry.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="add">Save changes</button>
        </form>

        {% endblock content %}
        
        <script src="" async defer></script>
    </body>
</html>

blog_posts/templates/blog_posts/entry.html
{% extends 'blog_posts/base.html' %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title %}<title>{{ blog }}</title>{% endblock title %}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {% block content %}

        <div class="section-title">
            <h2>{{ blog }} Entries</h2>
        </div>

        <div class="list-contents"> 
            {% for entry in entries %}
                <ul>
                    <li class="entry">
                        <h3>{{ entry }}</h3>
                        <p>{{ entry.text }}</p>
                        <p>{{ entry.date_added|date:'D, M n, Y' }}</p>
                        <button class="edit"><a href="{% url 'blog_posts:edit_entry' entry.id %}">Edit blog entry</a></button>
                        <button class="delete"><a href="{% url 'blog_posts:delete_entry' entry.id %}">Delete blog entry</a></button>
                    </li>
                    <hr></hr>
                </ul>
                {% empty %}
                    <p>There are no entries available</p>
            {% endfor %}

            <button class="add"><a href="{% url 'blog_posts:add_entry' blog.id %}">Add a new blog entry</a></button>
        </div>

        {% endblock content %}
        
        <script src="" async defer></script>
    </body>
</html>